from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel, Field


class RecognitionResponse(BaseModel):
    """
    Unified payload returned by the OCR stack.
    """

    type: Literal["formula", "text"] = Field(
        ...,
        description="Heuristic classification of the student's submission.",
    )
    latex: str = Field(..., description="Best-effort LaTeX transcription of the answer.")
    raw_text: str = Field(
        ..., description="Plain-text fallback generated by PaddleOCR for reference."
    )
    confidence: float = Field(
        ..., ge=0.0, le=1.0, description="Normalized confidence score from Pix2Text."
    )


class GradeRequest(BaseModel):
    student_latex: str = Field(
        ..., description="LaTeX string confirmed by the student via MathLive."
    )
    answer_latex: str = Field(
        ..., description="Ground-truth LaTeX that represents the model answer."
    )


class GradeResponse(BaseModel):
    correct: bool = Field(
        ..., description="Whether the normalized SymPy expressions are equivalent."
    )
    reason: str = Field(..., description="Human-readable explanation of the result.")
    normalized_student: Optional[str] = Field(
        None, description="Canonicalized SymPy string for the student's answer."
    )
    normalized_answer: Optional[str] = Field(
        None, description="Canonicalized SymPy string for the reference answer."
    )

